### PR TITLE
feat: add support for tagged docker images and error message for failed language server registration

### PR DESCRIPTION
**Pull request by sfavazza**

### CODE REVIEW

**Comment by factyy** [comment]
Please add the information regarding tagging into the readme

**Comment by sfavazza** [comment]
Sure thing, I inserted few words to indicate the support for tagged images. 

I also tried to refactor the YML configuration file example as I always found it a bit hard to read. I added the info based on what I figure out from the code. Let me know if anything is inaccurate.

**Comment by factyy** [comment]
@sfavazza , the documentation is awesome!

As for the comparison part imagine the following situation: a user uses a tagged image `image_name:tag`, so when looking for the existing image and image names are compared we are comparing both `image_name:tag` **and** `image_name:tag:latest` (which is meaningless) with existing images. So I propose not to add `latest` tag blindly and use it only when we are sure that the original image name is untagged (i.e. no colon (`:`) symbols in it). When you fix it this PR will be safely merged :)

Thanks!

**Comment by sfavazza** [comment]
@factyy , I applied your suggestion, now the `latest` tag is added only to untagged image names.

**Comment by factyy** [comment]
@sfavazza , looks good now! (BTW there is a nice string manipulation library out there: https://github.com/magnars/s.el , pretty useful in almost any situation)

**Comment by sfavazza** [comment]
Oh yeah, I saw sometimes the s-* functions, but not writing in lisp daily it's hard to keep track of the many goodies out there. Thanks for the merge!

**Comment by factyy** [comment]
Yeah, automated. Will be there in a few hours at most :)

**Pull request merged**
